# Generated by Django 5.1.1 on 2024-09-06 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sur_name',
            new_name='surname',
        ),
    ]
