# Generated by Django 5.1.1 on 2024-10-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatFile",
        ),
        migrations.AlterField(
            model_name="requesthistory",
            name="closed_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="requesthistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="telegramusermessage",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
