# Generated by Django 5.1.1 on 2024-10-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramusermessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
