# Generated by Django 5.1.1 on 2024-10-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_telegramusermessage_staff_telegramusermessage_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramusermessage',
            name='message_content',
            field=models.TextField(default='no message'),
        ),
        migrations.AddField(
            model_name='telegramusermessage',
            name='message_type',
            field=models.CharField(default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='telegramusermessage',
            name='message_file',
            field=models.FileField(blank=True, null=True, upload_to='messages/'),
        ),
    ]
