# Generated by Django 5.1.1 on 2024-10-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_telegramusermessage_message_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramusermessage',
            name='message_content',
        ),
        migrations.RemoveField(
            model_name='telegramusermessage',
            name='message_type',
        ),
        migrations.AddField(
            model_name='telegramusermessage',
            name='directory_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='telegramusermessage',
            name='message_file',
            field=models.FileField(upload_to='messages/'),
        ),
    ]
